version: '3'
services:
  front-nginx:
    container_name: "front-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - front-app
    ports:
      - 81:81
    volumes:
      - ./:/src

  front-app:
    container_name: "front-app"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
